host: 192.168.0.19
port: 8006
username: root@pam
tokenId: claude-test
tokenSecret: your-actual-token-secret
node: pve
rejectUnauthorized: false
name: test-status
created: '2025-07-31T21:00:00.000Z'
version: 0.1.0